# Generated by Django 3.2 on 2021-05-11 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monthly_Expenses', '0002_auto_20210511_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='MoneySpent',
            new_name='MoneyEarned',
        ),
        migrations.RenameField(
            model_name='income',
            old_name='ModeOfEarning',
            new_name='TypeoOfIncome',
        ),
        migrations.AddField(
            model_name='expense',
            name='SpentBy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Monthly_Expenses.user'),
        ),
        migrations.AddField(
            model_name='income',
            name='EarnedBy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Monthly_Expenses.user'),
        ),
        migrations.DeleteModel(
            name='Revenue',
        ),
    ]
