# Generated by Django 3.2 on 2021-05-11 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Monthly_Expenses', '0003_auto_20210511_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='SpentBy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='spent', to='Monthly_Expenses.user'),
        ),
        migrations.AlterField(
            model_name='income',
            name='EarnedBy',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='earned', to='Monthly_Expenses.user'),
        ),
    ]
