# Generated by Django 3.2 on 2021-05-11 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monthly_Expenses', '0004_auto_20210511_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='Date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='income',
            name='Date',
            field=models.DateTimeField(default=None),
        ),
    ]
