# Generated by Django 3.2 on 2021-05-11 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Monthly_Expenses', '0005_auto_20210511_2326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='Date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='income',
            name='Date',
            field=models.DateField(default=None),
        ),
    ]
